name: swe-vision
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - openai
      - jupyter_client
      - docker
      - flask
      - werkzeug
      - Pillow
      - regex
